# Dev Notebook

In [7]:
from pydantic import Field
from pydantic.dataclasses import dataclass
from datetime import datetime, timezone
import os
import requests
from requests.auth import HTTPBasicAuth
from requests.exceptions import HTTPError
from dotenv import load_dotenv
from typing import Union, Dict, Any, ClassVar, List
import pandas as pd

from stashies.dataclasses import YarnCompany, YarnFiber, Yarn

In [8]:
def post_request(
    url: str,
    data: Union[Dict[str, Any], None] = None,
    json: Union[Dict[str, Any], None] = None,
    API_KEY: str = "cbb3172b2f9543fd000cffe8545ee810",
    PASSWORD: str = "_NdUPofaVn3vjIjInKvLIwVxj2tg4Dk5Momswj1a",
) -> Any:
    """
    Function for making POST requests to Ravelry API.
    - Input
        - url: full API endpoint URL
        - data: form data to send (optional)
        - json: JSON data to send (optional)
    - output: Data returned from API
    """
    try:
        response = requests.post(
            url, 
            auth=HTTPBasicAuth(API_KEY, PASSWORD),
            data=data,
            json=json
        )
        response.raise_for_status()
    except HTTPError as http_err:
        print(f"HTTP error occurred: {http_err}")
    except Exception as err:
        print(f"Other error occurred: {err}")
    else:
        return response.json()
    
def get_request(
    url: str,
    API_KEY: str = "cbb3172b2f9543fd000cffe8545ee810",
    PASSWORD: str = "_NdUPofaVn3vjIjInKvLIwVxj2tg4Dk5Momswj1a",
) -> Any:
    """
    Function for making requests to Ravelry API.
    - Input
        - endpoint: end of API query e.x.`current_user.json`
    - output: Data returned from API
    """
    try:
        response = requests.get(url, auth=HTTPBasicAuth(API_KEY, PASSWORD))
        response.raise_for_status()
    except HTTPError as http_err:
        print(f"HTTP error occurred: {http_err}")
    except Exception as err:
        print(f"Other error occurred: {err}")
    else:
        # self.LOGGER.info(response.json())
        return response.json()

In [9]:
USERNAME: str = "thotsky"  # "KMLadybugCrochets"

# USERNAME: str = "KMLadybugCrochets"

In [10]:
stash = get_request(url=f"https://api.ravelry.com/people/{USERNAME}/stash/list.json")[
    "stash"
]
stash_ids = [entry["id"] for entry in stash]
stash_id = stash_ids[0]

# post_request(
#     f"https://api.ravelry.com/people/{USERNAME}/stash/{stash_id}.json",
#     data={"skeins": 6.5},
# )
item = get_request(
    url=f"https://api.ravelry.com/people/{USERNAME}/stash/{stash_id}.json"
)["stash"]
del item['yarn']['photos']
del item['yarn']['notes_html']

yarn = Yarn(**item['yarn'])

item

{'comments_count': 0,
 'created_at': '2025/09/12 02:00:29 -0400',
 'dye_lot': None,
 'favorites_count': 0,
 'handspun': False,
 'has_photo': False,
 'id': 31516215,
 'location': None,
 'permalink': 'moonshine',
 'updated_at': '2025/09/12 02:00:29 -0400',
 'user_id': 13618756,
 'name': 'Juniper Moon Farm Moonshine',
 'notes': None,
 'notes_html': None,
 'stash_status': {'id': 1, 'name': 'In stash'},
 'colorway_name': 'Purple',
 'color_family_name': None,
 'yarn_weight_name': 'Worsted',
 'long_yarn_weight_name': 'Worsted (9 wpi)',
 'personal_yarn_weight': None,
 'tag_names': [],
 'photos': [],
 'yarn': {'discontinued': False,
  'gauge_divisor': 1,
  'grams': 100,
  'id': 102743,
  'machine_washable': None,
  'max_gauge': 5.0,
  'min_gauge': 4.5,
  'name': 'Moonshine',
  'permalink': 'juniper-moon-farm-moonshine',
  'rating_average': 4.69,
  'rating_count': 1735,
  'rating_total': 8129,
  'texture': 'plied',
  'thread_size': None,
  'wpi': None,
  'yardage': 197,
  'min_needle_size': {'id': 7,
   'us': '7 ',
   'metric': 4.5,
   'us_steel': None,
   'crochet': False,
   'knitting': True,
   'hook': None,
   'name': 'US 7  - 4.5 mm',
   'pretty_metric': '4.5'},
  'max_needle_size': None,
  'min_hook_size': None,
  'max_hook_size': None,
  'personal_attributes': None,
  'yarn_company': {'id': 8214,
   'name': 'Juniper Moon Farm',
   'permalink': 'juniper-moon-farm',
   'url': 'http://www.fiberfarm.com/',
   'yarns_count': 97},
  'yarn_weight': {'crochet_gauge': None,
   'id': 12,
   'knit_gauge': '20',
   'max_gauge': None,
   'min_gauge': None,
   'name': 'Worsted',
   'ply': '10',
   'wpi': '9'},
  'yarn_fibers': [{'id': 200544,
    'percentage': 20,
    'fiber_type': {'animal_fiber': True,
     'id': 9,
     'name': 'Silk',
     'synthetic': False,
     'vegetable_fiber': False},
    'fiber_category': {'id': 167, 'name': 'Silk', 'permalink': 'silk'}},
   {'id': 200542,
    'percentage': 40,
    'fiber_type': {'animal_fiber': True,
     'id': 3,
     'name': 'Wool',
     'synthetic': False,
     'vegetable_fiber': False},
    'fiber_category': {'id': 1, 'name': 'Wool', 'permalink': 'wool'}},
   {'id': 200543,
    'percentage': 40,
    'fiber_type': {'animal_fiber': True,
     'id': 14,
     'name': 'Alpaca',
     'synthetic': False,
     'vegetable_fiber': False},
    'fiber_category': {'id': 136,
     'name': 'Alpaca',
     'permalink': 'alpaca',
     'parent': {'id': 132, 'name': 'Camelid', 'permalink': 'camelid'}}}],
  'yarn_attributes': [{'description': 'wash by hand',
    'id': 4,
    'name': 'Hand Wash',
    'permalink': 'hand-wash',
    'yarn_attribute_group': {'id': 8, 'name': 'Care', 'permalink': 'care'}},
   {'description': 'made up of a single strand of yarn',
    'id': 36,
    'name': 'Single ply',
    'permalink': 'single-ply',
    'yarn_attribute_group': {'id': 15, 'name': 'Ply', 'permalink': 'ply'}},
   {'description': 'yarn in which the fibers appear to be twisted in a direction like the letter Z when the yarn is held vertically\r',
    'id': 80,
    'name': 'Z Twist',
    'permalink': 'z-twist',
    'yarn_attribute_group': {'id': 13,
     'name': 'Construction',
     'permalink': 'construction'}},
   {'description': 'dyed by machine',
    'id': 12,
    'name': 'Machine dyed',
    'permalink': 'machine-dyed',
    'yarn_attribute_group': {'id': 11, 'name': 'Dye', 'permalink': 'dye'}},
   {'description': 'needs to be wound into a ball before use',
    'id': 75,
    'name': 'Winding required',
    'permalink': 'winding-required',
    'yarn_attribute_group': {'id': 18,
     'name': 'Put up',
     'permalink': 'put-up'}},
   {'description': 'dyed in a single hue with no variation',
    'id': 78,
    'name': 'Solid color',
    'permalink': 'solid',
    'yarn_attribute_group': {'id': 12,
     'name': 'Color',
     'permalink': 'color'}}],
  'yarn_provenance': []},
 'packs': [{'id': 134290871,
   'primary_pack_id': None,
   'project_id': None,
   'skeins': 7.0,
   'stash_id': 31516215,
   'total_grams': 700,
   'total_meters': 1261.0,
   'total_ounces': 24.69,
   'total_yards': 1379.0,
   'yarn_id': 102743,
   'shop_name': None,
   'colorway': 'Purple',
   'quantity_description': '7 skeins = 1379.0 yards (1261.0m)',
   'personal_name': None,
   'dye_lot': None,
   'color_family_id': None,
   'grams_per_skein': 100,
   'yards_per_skein': 197.0,
   'meters_per_skein': 180.1,
   'ounces_per_skein': 3.53,
   'prefer_metric_weight': True,
   'prefer_metric_length': False,
   'shop_id': None,
   'thread_size': None,
   'color_attributes': [],
   'total_paid': None,
   'total_paid_currency': None},
  {'id': 134290872,
   'primary_pack_id': 134290871,
   'project_id': None,
   'skeins': 5.5,
   'stash_id': 31516215,
   'total_grams': 550,
   'total_meters': 990.9,
   'total_ounces': 19.4,
   'total_yards': 1083.5,
   'yarn_id': 102743,
   'shop_name': None,
   'colorway': 'Purple',
   'quantity_description': None,
   'personal_name': None,
   'dye_lot': None,
   'color_family_id': None,
   'grams_per_skein': None,
   'yards_per_skein': None,
   'meters_per_skein': None,
   'ounces_per_skein': None,
   'prefer_metric_weight': True,
   'prefer_metric_length': False,
   'shop_id': None,
   'thread_size': None,
   'color_attributes': [],
   'total_paid': None,
   'total_paid_currency': None},
  {'id': 135830458,
   'primary_pack_id': 134290871,
   'project_id': None,
   'skeins': 1.0,
   'stash_id': 31516215,
   'total_grams': 100,
   'total_meters': 180.1,
   'total_ounces': 3.53,
   'total_yards': 197.0,
   'yarn_id': 102743,
   'shop_name': None,
   'colorway': 'Purple',
   'quantity_description': '1 skeins = 197.0 yards (180.1m)',
   'personal_name': None,
   'dye_lot': None,
   'color_family_id': None,
   'grams_per_skein': 100,
   'yards_per_skein': 197.0,
   'meters_per_skein': 180.1,
   'ounces_per_skein': 3.53,
   'prefer_metric_weight': True,
   'prefer_metric_length': False,
   'shop_id': None,
   'thread_size': None,
   'color_attributes': [],
   'total_paid': None,
   'total_paid_currency': None},
  {'id': 135882039,
   'primary_pack_id': 134290871,
   'project_id': None,
   'skeins': 0.5,
   'stash_id': 31516215,
   'total_grams': 50,
   'total_meters': 90.1,
   'total_ounces': 1.76,
   'total_yards': 98.5,
   'yarn_id': 102743,
   'shop_name': None,
   'colorway': 'Purple',
   'quantity_description': '0.5 skeins = 98.5 yards (90.1m)',
   'personal_name': None,
   'dye_lot': None,
   'color_family_id': None,
   'grams_per_skein': 100,
   'yards_per_skein': 197.0,
   'meters_per_skein': 180.1,
   'ounces_per_skein': 3.53,
   'prefer_metric_weight': True,
   'prefer_metric_length': False,
   'shop_id': None,
   'thread_size': None,
   'color_attributes': [],
   'total_paid': None,
   'total_paid_currency': None}],
 'user': {'id': 13618756,
  'username': 'Thotsky',
  'tiny_photo_url': None,
  'small_photo_url': None,
  'photo_url': None,
  'profile_country_code': None}}

In [11]:
# 
packs = item['packs']
packs[0]['timestamp'] = datetime.strptime(item['created_at'], '%Y/%m/%d %H:%M:%S %z')
current_time = datetime.now(timezone.utc)
current_time = current_time.strftime('%Y/%m/%d %H:%M:%S %z')



df = pd.DataFrame(packs)
df

,id,primary_pack_id,project_id,skeins,stash_id,total_grams,total_meters,total_ounces,total_yards,yarn_id,...,meters_per_skein,ounces_per_skein,prefer_metric_weight,prefer_metric_length,shop_id,thread_size,color_attributes,total_paid,total_paid_currency,timestamp
0,134290871,NaN,None,7.0,31516215,700,1261.0,24.69,1379.0,102743,...,180.1,3.53,True,False,None,None,[],None,None,2025-09-12 02:00:29-04:00
1,134290872,134290871.0,None,5.5,31516215,550,990.9,19.40,1083.5,102743,...,NaN,NaN,True,False,None,None,[],None,None,NaT
2,135830458,134290871.0,None,1.0,31516215,100,180.1,3.53,197.0,102743,...,180.1,3.53,True,False,None,None,[],None,None,NaT
3,135882039,134290871.0,None,0.5,31516215,50,90.1,1.76,98.5,102743,...,180.1,3.53,True,False,None,None,[],None,None,NaT

In [12]:
df[['total_grams', 'total_meters', 'total_ounces', 'total_yards', 'timestamp']]

,total_grams,total_meters,total_ounces,total_yards,timestamp
0,700,1261.0,24.69,1379.0,2025-09-12 02:00:29-04:00
1,550,990.9,19.40,1083.5,NaT
2,100,180.1,3.53,197.0,NaT
3,50,90.1,1.76,98.5,NaT